triage:
  label: triage
  dryRun: false

support:
  label: support
  message: >
    Thanks for the issue! This issue appears to be a support request. We use this issue tracker exclusively for
    bug reports and feature requests. Please use our [forum](https://forum.ionicframework.com) or our
    [slack channel](https://ionicworldwide.herokuapp.com/) for questions about the framework.
    
    
    Thank you for using Ionic!
  close: true
  lock: true
  dryRun: false

incomplete:
  label: missing template
  message: >
    Hello! While we appreciate you opening an issue with us I am going to close this issue and ask that you
    open a new issue that has the template fully filled out, please. Thanks for using Ionic!
  close: true
  lock: true
  dryRun: false
  
