version: 2

aliases:
  - &restore-cache
      keys:
        - dependency-cache-{{ checksum "package.json" }}-2

  - &save-cache
      key: dependency-cache-{{ checksum "package.json" }}-2
      paths:
        - node_modules

  - &restore-cache-core
      keys:
        - dependency-cache-{{ checksum "core/package.json" }}-2

  - &save-cache-core
      key: dependency-cache-{{ checksum "core/package.json" }}-2
      paths:
        - core/node_modules


defaults: &defaults
  docker:
    - image: circleci/node:latest-browsers
  working_directory: /tmp/workspace

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-cache
      - run: npm install
      - save_cache: *save-cache
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  build-core:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-core
      - run:
          command: npm install
          working_directory: /tmp/workspace/core
      - save_cache: *save-cache-core
      - run:
          command: npm run build # --max-workers 1 --debug
          working_directory: /tmp/workspace/core
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"

  test-core-lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run lint
          working_directory: /tmp/workspace/core

  test-core-spec:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.spec
          working_directory: /tmp/workspace/core

  test-core-treeshake:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: npm run test.treeshake
          working_directory: /tmp/workspace/core

workflows:
  version: 2
  build:
    jobs:
      - build
      - build-core:
          requires: [build]
      - test-core-lint:
          requires: [build-core]
      - test-core-spec:
          requires: [build-core]
      - test-core-treeshake:
          requires: [build-core]
